import { WeatherConditionType } from '../types/weather';

export const weatherDescriptions: { [key: number]: WeatherConditionType } = {
    0: { description: 'selkeää', color: '#ffd900ff' },
    1: { description: 'enimmäkseen selkeää', color: '#ffdc2fff' },
    2: { description: 'puolipilvistä', color: '#C0C0C0' },
    3: { description: 'enimmäkseen pilvistä', color: '#A9A9A9' },
    4: { description: 'pilvistä', color: '#808080' },
    5: { description: 'sumua', color: '#696969' },
    6: { description: 'tihkusadetta', color: '#B0E0E6' },
    7: { description: 'jäätävää tihkua', color: '#00CED1' },
    8: { description: 'jäätävää sadetta', color: '#4682B4' },
    9: { description: 'yksittäisiä sadekuuroja', color: '#1E90FF' },
    10: { description: 'paikoin sadekuuroja', color: '#87CEFA' },
    11: { description: 'sadekuuroja', color: '#6495ED' },
    12: { description: 'puolipilvistä ja ajoittain heikkoa vesisadetta', color: '#ADD8E6' },
    13: { description: 'puolipilvistä ja ajoittain kohtalaista vesisadetta', color: '#87CEEB' },
    14: { description: 'puolipilvistä ja ajoittain voimakasta vesisadetta', color: '#4682B4' },
    15: { description: 'enimmäkseen pilvistä ja ajoittain heikkoa vesisadetta', color: '#778899' },
    16: { description: 'enimmäkseen pilvistä ja ajoittain kohtalaista vesisadetta', color: '#708090' },
    17: { description: 'enimmäkseen pilvistä ja ajoittain voimakasta vesisadetta', color: '#2F4F4F' },
    18: { description: 'heikkoa vesisadetta', color: '#B0C4DE' },
    21: { description: 'kohtalaista vesisadetta', color: '#4169E1' },
    22: { description: 'voimakasta vesisadetta', color: '#1E90FF' },
    23: { description: 'puolipilvistä ja ajoittain heikkoa räntäsadetta tai räntäkuuroja', color: '#87CEFA' },
    24: { description: 'puolipilvistä ja ajoittain kohtalaista räntäsadetta tai räntäkuuroja', color: '#4682B4' },
    25: { description: 'puolipilvistä ja ajoittain voimakasta räntäsadetta tai räntäkuuroja', color: '#4169E1' },
    26: { description: 'enimmäkseen pilvistä ja ajoittain heikkoa räntäsadetta tai räntäkuuroja', color: '#778899' },
    27: { description: 'enimmäkseen pilvistä ja ajoittain kohtalaista räntäsadetta tai räntäkuuroja', color: '#708090' },
    28: { description: 'enimmäkseen pilvistä ja ajoittain voimakasta räntäsadetta tai räntäkuuroja', color: '#2F4F4F' },
    29: { description: 'heikkoa räntäsadetta', color: '#B0C4DE' },
    30: { description: 'kohtalaista räntäsadetta', color: '#4682B4' },
    31: { description: 'voimakasta räntäsadetta', color: '#1E90FF' },
    32: { description: 'puolipilvistä ja ajoittain heikkoa lumisadetta tai lumikuuroja', color: '#F0F8FF' },
    33: { description: 'puolipilvistä ja ajoittain kohtalaista lumisadetta tai lumikuuroja', color: '#E6E6FA' },
    34: { description: 'puolipilvistä ja ajoittain sakeaa lumisadetta tai lumikuuroja', color: '#DCDCDC' },
    35: { description: 'enimmäkseen pilvistä ja ajoittain heikkoa lumisadetta tai lumikuuroja', color: '#C0C0C0' },
    36: { description: 'enimmäkseen pilvistä ja ajoittain kohtalaista lumisadetta tai lumikuuroja', color: '#B0C4DE' },
    37: { description: 'enimmäkseen pilvistä ja ajoittain sakeaa lumisadetta tai lumikuuroja', color: '#A9A9A9' },
    38: { description: 'heikkoa lumisadetta', color: '#F5F5F5' },
    39: { description: 'kohtalaista lumisadetta', color: '#D3D3D3' },
    40: { description: 'runsasta lumisadetta', color: '#DCDCDC' },
    41: { description: 'yksittäisiä raekuuroja', color: '#E0FFFF' },
    42: { description: 'paikoin raekuuroja', color: '#B0E0E6' },
    43: { description: 'raekuuroja', color: '#AFEEEE' },
    44: { description: 'yksittäisiä ukkoskuuroja', color: '#87CEFA' },
    45: { description: 'paikoin ukkoskuuroja', color: '#87CEEB' },
    46: { description: 'ukkoskuuroja', color: '#4682B4' },
};